### ISSUE TITLE
Wrong correspondent nickname and ID on conversation shortcut

### ISSUE THREAD

**Issue by nsmaniotto** [nsmaniotto/Distributed-Chat-System#11]
Steps to reproduce the issue:

1. Launch 4 local clients (here Local1, Local2, Local3, Local4)
2. From Local4, send a message to Local1

--> Local1 receives the message but displays a notification from Local3:
![image](https://user-images.githubusercontent.com/62234196/106931393-75e3d280-670e-11eb-835e-2110a25cf945.png)

3. From Local1, send a message to Local3, therefore, respond to the previous notification

--> Local4 receives the message from Local1
![image](https://user-images.githubusercontent.com/62234196/106931701-c52a0300-670e-11eb-883a-59f36eb40551.png)

**Comment by Rob174** [comment]
On [this](https://github.com/nsmaniotto/Distributed-Chat-System/blob/a6e5ae81cdbb31315fc73d6bbe9a49e8479ed82c/IDChatSystem/src/main/java/project/insa/idchatsystem/Conversations/ConversationHandler/LocalConversationHandler.java#L85) line of the handler how do you differentiate conversations as we are running all conversations on the same computer ?
Could it be the cause of the problem ?

**Comment by nsmaniotto** [comment]
Issue fixed with commit fd68689c3f09f501ee61c7409429553950c61371 by sending source information at conversation creation in order to confirm its identity.
